name: blood_donation
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  loading_overlay: ^0.3.0
  date_format: ^2.0.4
  firebase_messaging: ^11.2.7
  flutter_datetime_picker: ^1.5.1
  cupertino_icons: ^1.0.2
  image_picker: ^0.7.5+2
  get_it: ^6.0.0
  provider: ^5.0.0
  shared_preferences: ^2.0.5
  shimmer: ^1.1.2
  dio: ^4.0.0
  fluro: ^2.0.3
  path_provider: ^2.0.1
  connectivity: ^3.0.2
  location: ^4.3.0
  universal_ui: ^0.0.8
  image: ^3.0.2
  permission_handler: ^8.1.6
  bottom_sheet: ^1.0.1
  flutter_slidable: ^0.5.7
  flutter_dash: ^0.0.1
  timeline_tile: ^2.0.0
  sizer: ^2.0.15
  flutter_rating_bar: ^4.0.0
  mime: ^0.9.7
  email_validator: ^2.0.1
  loader_overlay: ^2.0.6
  loading_animation_widget: ^1.1.0+5
  fl_chart: ^0.55.0
  date_time_picker: ^2.1.0
  timelines: ^0.1.0
  intl: ^0.17.0
  flutter_local_notifications: ^9.9.1
  badges: ^2.0.3

dependency_overrides:
  firebase_messaging_platform_interface: 3.1.6
  
dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^2.1.6
  flutter_test:
    sdk: flutter

flutter_native_splash:
  background_image: "assets/image/splash_bg.png"
  image: "assets/image/splash_logo.png"
  android_disable_fullscreen: false
  android: true
  android_gravity: center
  
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.png"

flutter:

  uses-material-design: true

  assets:
    - assets/icon/
    - assets/image/
    - assets/language/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Light.ttf
          weight: 200
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700